spring.application.name=Carepulse

# ==========================================
# TEAM SETUP: DATABASE CONNECTION SETTINGS
# ==========================================

# 1. DATABASE NAME: Change 'hospital_db' to whatever you named your database in pgAdmin
spring.datasource.url=jdbc:postgresql://localhost:5432/hospital_db

# 2. USERNAME: Default is 'postgres'. Change this if you used a different superuser name
spring.datasource.username=postgres

# 3. PASSWORD: DO NOT type your password here!
# Instead, add an Environment Variable named 'DB_PASSWORD' inside your IntelliJ run configurations.
spring.datasource.password=${DB_PASSWORD}


# ==========================================
# JPA / HIBERNATE SETTINGS (Leave these alone)
# ==========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect